<?php

/**
 * @file
 * Contains block_groups.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Config\Entity\ConfigEntityType;

/**
 * Implements hook_help().
 */
function block_groups_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_groups module.
    case 'help.page.block_groups':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function block_groups_theme() {
  $theme = [];

  return $theme;
}
function block_groups_entity_type_alter(array &$entity_types) {
  /**
   * @var ConfigEntityType $block_type;
   */
  $block_type = $entity_types['block'];
  $b = ';';
  $block_type->setHandlerClass('list_builder', 'Drupal\block_groups\BlockGroupedListBuilder');
}
