<?php

/**
 * @file
 * Contains block_visibility_groups.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Config\Entity\ConfigEntityType;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function block_visibility_groups_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_visibility_groups module.
    case 'help.page.block_visibility_groups':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

function block_visibility_groups_entity_type_alter(array &$entity_types) {
  /**
   * @var ConfigEntityType $block_type;
   */
  $block_type = $entity_types['block'];
  $block_type->setHandlerClass('list_builder', 'Drupal\block_visibility_groups\BlockVisibilityGroupedListBuilder');
}

/**
 * Implements hook_form_alter().
 */
function block_visibility_groups_form_block_form_alter(&$form, &$form_state, $form_id) {
  $form['actions']['submit']['#submit'][] = 'block_visibility_groups_block_form_submit';

}
function block_visibility_groups_block_form_submit($form , FormStateInterface $form_state) {
  $redirect = $form_state->getRedirect();
  /** @var Url $redirect */

  if ($redirect && $redirect instanceof Url) {
    $block_visibility_group_query = $form_state->getTemporaryValue('block_visibility_group_query');
    if ($block_visibility_group_query) {
      $query = $redirect->getOption('query');
      $query['block_visibility_group'] = $block_visibility_group_query;
      $redirect->setOption('query', $query);
    }
  }
}
