<?php
/**
 * Author: Ted Bowman
 * Date: 8/22/15
 * Time: 6:22 PM
 */

namespace Drupal\block_groups;


use Drupal\block\BlockListBuilder;
use Drupal\Core\Form\FormStateInterface;

class BlockGroupedListBuilder extends BlockListBuilder{
  public function buildForm(array $form, FormStateInterface $form_state) {
    $form = parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
    $form['extra'] = array(
      '#type' => 'markup',
      '#markup' => '<h1>Hi</h1>',
    );
    return $form;
  }

  protected function buildBlocksForm() {
    $form = parent::buildBlocksForm(); // TODO: Change the autogenerated stub
    foreach ($form as $row_key => $row_info) {
      if (isset($row_info['title']['#url'])) {
        /** @var \Drupal\Core\Url $url */
        $url = &$row_info['title']['#url'];
        $query = $url->getOption('query');
        $query['block_group'] = 'blocker';
        $url->setOption('query', $query);
      }
    }
    return $form;

  }

  protected function getEntityIds() {
    $entity_ids = parent::getEntityIds();
    $entities = $this->storage->loadMultipleOverrideFree($entity_ids);

    // Sort the entities using the entity class's sort() method.
    // See \Drupal\Core\Config\Entity\ConfigEntityBase::sort().
    uasort($entities, array($this->entityType->getClass(), 'sort'));
    return $entity_ids;
  }


}

